# Tensor Basics



In [ ]:
import torch

**Tensor structure**


xxxx = method \
zzzz = datatype specification \
torch.xxxx(size, dtype = zzzz)


In [ ]:
#Empty Tensor 

x = torch.empty(3,2)
print(x)

# Random tensor
x = torch.rand(2,1)
print(x)

# Zeros tensor
x= torch.zeros(1,4)
print(x)

# Ones tensor
x = torch.ones(1,2, dtype=torch.float16)
print(x)

tensor([[-1.6603e-08,  3.0771e-41],
        [ 3.3631e-44,  0.0000e+00],
        [        nan,  1.8933e+00]])
tensor([[0.3013],
        [0.6987]])
tensor([[0., 0., 0., 0.]])
tensor([[1., 1.]], dtype=torch.float16)


In [ ]:
# tensor from a list

x = torch.tensor([2.1, 3, 4])
print(x)

tensor([2.1000, 3.0000, 4.0000])


In [ ]:
#Tensor Operations

x = torch.rand(2,2)
y = torch.rand(2,2)
print("x:   ",x)
print("y:   ",y)

z = x + y 
#or
z = torch.add(x,y)
print("Sum:   ",z)


# z = y-x
z = y - x
z = torch.sub(x,y)

print("Substraction:    ",z)


# z = y*x
z = y * x
z = torch.mul(x,y)

print("Multiplication:    ",z)


# y = y/x
z = x / y
z = torch.div(x,y)

print("Division:    ",z)



x:    tensor([[0.3144, 0.6775],
        [0.5592, 0.8624]])
y:    tensor([[0.1296, 0.2820],
        [0.5383, 0.0517]])
Sum:    tensor([[0.4440, 0.9596],
        [1.0975, 0.9141]])
Substraction:     tensor([[0.1848, 0.3955],
        [0.0208, 0.8107]])
Multiplication:     tensor([[0.0407, 0.1911],
        [0.3010, 0.0446]])
Division:     tensor([[ 2.4263,  2.4023],
        [ 1.0387, 16.6757]])


if the metod have a "_", its in place operation

In [ ]:
#Tensor Operations in place ("_")

x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

# y = y+x
y.add_(x)

print(y)

# y = y-x
y.sub_(x)

print(y)

# y = y*x
y.mul_(x)

print(y)

# y = y/x
y.div_(x)

print(y)


tensor([[0.1773, 0.2761],
        [0.0844, 0.9214]])
tensor([[0.6470, 0.9542],
        [0.7338, 0.9797]])
tensor([[0.8243, 1.2303],
        [0.8182, 1.9011]])
tensor([[0.6470, 0.9542],
        [0.7338, 0.9797]])
tensor([[0.1147, 0.2634],
        [0.0620, 0.9027]])
tensor([[0.6470, 0.9542],
        [0.7338, 0.9797]])


In [ ]:
#Tensor manipulation

x = torch.rand(4,3)
print(x)

print("first colum and all rows", x[:,1])

print("first row and all colums", x[1,:])

print("Actual value of one element", x[2,2].item())



tensor([[0.0139, 0.7671, 0.2913],
        [0.0322, 0.2972, 0.3717],
        [0.2371, 0.1559, 0.0857],
        [0.3789, 0.2598, 0.5598]])
first colum and all rows tensor([0.7671, 0.2972, 0.1559, 0.2598])
first row and all colums tensor([0.0322, 0.2972, 0.3717])
Actual valuo of one element 0.0856660008430481


In [ ]:
# Reshaping

x = torch.rand(4,4)
print(x)

# Transform to one dimension
y = x.view(4*4)
print(y)

# Transfor to a specific Dimension

y = x.view(-1,8) # -1 is for the automatic ajusting to dimesion 8
print(y)
print(y.size())



tensor([[0.9894, 0.4777, 0.9924, 0.2222],
        [0.6748, 0.2655, 0.2133, 0.9470],
        [0.0293, 0.4964, 0.3758, 0.0894],
        [0.8140, 0.2623, 0.8837, 0.8998]])
tensor([0.9894, 0.4777, 0.9924, 0.2222, 0.6748, 0.2655, 0.2133, 0.9470, 0.0293,
        0.4964, 0.3758, 0.0894, 0.8140, 0.2623, 0.8837, 0.8998])
tensor([[0.9894, 0.4777, 0.9924, 0.2222, 0.6748, 0.2655, 0.2133, 0.9470],
        [0.0293, 0.4964, 0.3758, 0.0894, 0.8140, 0.2623, 0.8837, 0.8998]])
torch.Size([2, 8])


In [ ]:
# Convertion tensor to numpy

import numpy as np

x = torch.rand(1,3)
print(x)

y = x.numpy()
print(y)
print("Tensor:        ",x)
print("Numpy array:   ",y)


# Both are point to the same memory location
print("IMPORTANT, Both are point to the same memory location:")
x.add_(1)
print("Tensor:        ",x)
print("Numpy array:   ",y)



# Convertion numpy to tensor

x = np.ones(5)
y = torch.from_numpy(x)
print("Numpy array:   ",x)
print("Tensor:        ",y)


# Both are point to the same memory location

print("IMPORTANT, Both are point to the same memory location:")
x -= 1
print("Numpy array:   ",x)
print("Tensor:        ",y)




"""
Both are point to the same memory location, only if tensor is in CPU
"""
# Specifing a device

x = torch.zeros(2, device = "cpu")

#x = x.to("cuda") # Moving tensor to other device



tensor([[0.8428, 0.9322, 0.4947]])
[[0.84275556 0.9321718  0.49467254]]
Tensor:         tensor([[0.8428, 0.9322, 0.4947]])
Numpy array:    [[0.84275556 0.9321718  0.49467254]]
IMPORTANT, Both are point to the same memory location:
Tensor:         tensor([[1.8428, 1.9322, 1.4947]])
Numpy array:    [[1.8427556 1.9321718 1.4946725]]
Numpy array:    [1. 1. 1. 1. 1.]
Tensor:         tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
IMPORTANT, Both are point to the same memory location:
Numpy array:    [0. 0. 0. 0. 0.]
Tensor:         tensor([0., 0., 0., 0., 0.], dtype=torch.float64)
